import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Light Theme Colors
        "surface": "#f2f7f6",
        "surface-dim": "#cbd5e1",
        "surface-bright": "#f2f7f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ecf4f3",
        "surface-container": "#e2e8f0",
        "surface-container-high": "#cbd5e1",
        "surface-container-highest": "#94a3b8",
        "on-surface": "#0f172a",
        "on-surface-variant": "#334155",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "outline": "#64748b",
        "outline-variant": "#cbd5e1",
        "surface-tint": "#0f766e",
        "primary": "#10b981",
        "on-primary": "#ffffff",
        "primary-container": "#0d9488",
        "on-primary-container": "#ccfbf1",
        "inverse-primary": "#6ee7b7",
        "secondary": "#0f766e",
        "on-secondary": "#ffffff",
        "secondary-container": "#a7f3d0",
        "on-secondary-container": "#064e3b",
        "tertiary": "#0f766e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#115e59",
        "on-tertiary-container": "#99f6e4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d1fae5",
        "primary-fixed-dim": "#a7f3d0",
        "on-primary-fixed": "#064e3b",
        "on-primary-fixed-variant": "#047857",
        "secondary-fixed": "#ccfbf1",
        "secondary-fixed-dim": "#99f6e4",
        "on-secondary-fixed": "#115e59",
        "on-secondary-fixed-variant": "#134e4a",
        "tertiary-fixed": "#ccfbf1",
        "tertiary-fixed-dim": "#99f6e4",
        "on-tertiary-fixed": "#115e59",
        "on-tertiary-fixed-variant": "#134e4a",
        "background": "#f2f7f6",
        "on-background": "#0f172a",
        "surface-variant": "#ecf4f3",
        "surface-cream": "#f0fdf4",
        "deep-forest": "#0f766e",
        "ethereal-purple": "#06b6d4",
        "ink-charcoal": "#0f172a",
        "muted-sage": "#e6f4f1",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1.0rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-width-content": "1200px",
        "stack-md": "16px",
        "container-padding": "24px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "unit": "4px",
        // Stitch Spacing
        "margin-desktop": "48px",
        "container-max": "1200px",
        "base": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "sans": ["var(--font-inter)", "sans-serif"],
        "mono": ["var(--font-mono)", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "label-mono": ["var(--font-mono)", "monospace"],
        "display-lg": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
